import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/sidebar";  // Sidebar component
import Header from "../components/header";    // Header component

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex w-full`}>
        <Sidebar />
        <div className="">
          <Header />
          <main className="">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
