import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/sidebar";
import Header from "../components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex h-screen`}>
        {/* Sidebar - Takes up 1/4th of the width */}
        <Sidebar />

        {/* Main Content Area */}
        <div className="flex flex-col w-full">
          {/* Header */}
          <Header />

          {/* Main Body */}
          <main className="p-6 bg-gray-100 min-h-full">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
